# Generated by Django 3.1.5 on 2021-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
