# Generated by Django 3.1.7 on 2021-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0002_auto_20210217_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_name', models.CharField(max_length=50)),
                ('factors', models.DecimalField(decimal_places=2, max_digits=4)),
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Unverified', max_length=10)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('verify_code', models.TextField(max_length=10)),
                ('train_name', models.CharField(max_length=50)),
                ('train_id', models.IntegerField()),
                ('frome', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=50)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('buyer_id', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('fair', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('train_name', models.CharField(max_length=50)),
                ('factors', models.DecimalField(decimal_places=2, max_digits=4)),
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('offday', models.CharField(max_length=10)),
                ('stopages', models.CharField(max_length=5000)),
                ('ac_b_seat', models.IntegerField()),
                ('ac_s_seat', models.IntegerField()),
                ('f_b_seat', models.IntegerField()),
                ('f_s_seat', models.IntegerField()),
                ('snigdha_seat', models.IntegerField()),
                ('s_chair_seat', models.IntegerField()),
                ('sulov_seat', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
