# Generated by Django 3.1.7 on 2021-02-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0004_fritrains_montrains_sattrains_suntrains_thutrains_tuetrains_wedtrains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_b', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ac_s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('f_b', models.DecimalField(decimal_places=2, max_digits=4)),
                ('f_s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snigdha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('s_chair', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sulov', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
