# Generated by Django 3.1.7 on 2021-03-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0007_auto_20210329_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
